// Proposed permissions manifest for plugin 'core-executor-debug'.
// Generated by 'kaizen plugin dev --observe'. Review and paste into
// your plugin's default export under the `permissions` field.

export const permissions = {
  "tier": "scoped",
  "events": {
    "subscribe": [
      "session:end",
      "session:response",
      "session:start",
      "session:user_message",
      "tool:after",
      "tool:before"
    ]
  }
} as const;
