export interface Vocab {
  readonly HARNESS_START: "harness:start";
  readonly HARNESS_END: "harness:end";
  readonly HARNESS_ERROR: "harness:error";
  readonly HARNESS_EXIT_REQUESTED: "harness:exit-requested";
  readonly SESSION_CREATED: "session:created";
  readonly SESSION_RESUMED: "session:resumed";
  readonly SESSION_DELETED: "session:deleted";
  readonly SESSION_ACTIVE_CHANGED: "session:active-changed";
  readonly SESSION_RENAMED: "session:renamed";
  readonly SESSION_HANDOFF: "session:handoff";
  readonly INPUT_SUBMIT: "input:submit";
  readonly INPUT_HANDLED: "input:handled";
  readonly CONVERSATION_USER_MESSAGE: "conversation:user-message";
  readonly CONVERSATION_ASSISTANT_MESSAGE: "conversation:assistant-message";
  readonly CONVERSATION_SYSTEM_MESSAGE: "conversation:system-message";
  readonly CONVERSATION_CLEARED: "conversation:cleared";
  readonly TURN_START: "turn:start";
  readonly TURN_END: "turn:end";
  readonly TURN_CANCEL: "turn:cancel";
  readonly TURN_ERROR: "turn:error";
  readonly LLM_BEFORE_CALL: "llm:before-call";
  readonly LLM_REQUEST: "llm:request";
  readonly LLM_TOKEN: "llm:token";
  readonly LLM_REASONING: "llm:reasoning";
  readonly LLM_TOOL_CALL: "llm:tool-call";
  readonly LLM_DONE: "llm:done";
  readonly LLM_ERROR: "llm:error";
  readonly TOOL_BEFORE_EXECUTE: "tool:before-execute";
  readonly TOOL_EXECUTE: "tool:execute";
  readonly TOOL_RESULT: "tool:result";
  readonly TOOL_ERROR: "tool:error";
  readonly TOOL_PROGRESS: "tool:progress";
  readonly CODEMODE_CODE_EMITTED: "codemode:code-emitted";
  readonly CODEMODE_BEFORE_EXECUTE: "codemode:before-execute";
  readonly CODEMODE_RESULT: "codemode:result";
  readonly CODEMODE_ERROR: "codemode:error";
  readonly SKILL_LOADED: "skill:loaded";
  readonly SKILL_AVAILABLE_CHANGED: "skill:available-changed";
  readonly STATUS_ITEM_UPDATE: "status:item-update";
  readonly STATUS_ITEM_CLEAR: "status:item-clear";
  readonly PROMPT_REBUILT: "prompt:rebuilt";
  readonly PROMPT_RELOAD: "prompt:reload";
  readonly TOOLS_REGISTERED: "tools:registered";
  readonly TOOLS_UNREGISTERED: "tools:unregistered";
  readonly MCP_REGISTRATION_CONFLICT: "mcp:registration-conflict";
}
export type EventName = Vocab[keyof Vocab];

export const CONTRACT_ID = "events:vocabulary" as const;
export const DESCRIPTION = "Canonical event-name vocabulary for the harness.";
